openapi: 3.0.1
info:
  title: ZendeskApi
  version: 1.0.0
servers:
  - url: 'https://domain.zendesk.com/api'
paths:
  /v2/macros/{macroId}:
    get:
      security:
        - basicAuth: []
      tags:
        - macros
      summary: Returns macro by id
      parameters:
        - name: macroId
          required: true
          schema:
            type: number
          in: path
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Macro'
        '404':
          description: Macro not found
  /v2/users/me:
    get:
      security:
        - basicAuth: []
      tags:
        - users
      summary: Returns self user
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
  /v2/users/{userId}/groups:
    get:
      security:
        - basicAuth: []
      tags:
        - groups
      summary: Returns user's groups
      parameters:
        - name: userId
          required: true
          schema:
            type: number
          in: path
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        '404':
          description: User not found
  /v2/tickets:
    post:
      security:
        - basicAuth: []
      tags:
        - tickets
      summary: Create new ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ticket
              properties:
                ticket:
                  $ref: '#/components/schemas/TicketDTO'
      responses:
        '200':
          description: Ticket created succesfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
        '422':
          description: Server is unable to process the contained instructions
  /v2/tickets/{ticketId}:
    put:
      security:
        - basicAuth: []
      tags:
        - tickets
      summary: Update ticket
      parameters:
        - name: ticketId
          required: true
          schema:
            type: number
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ticket
              properties:
                ticket:
                  $ref: '#/components/schemas/TicketDTO'
      responses:
        '200':
          description: Ticket created succesfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
        '404':
          description: Ticket not found
  /support/apps/installations/{appId}:
    get:
      parameters:
        - name: appId
          schema:
            type: number
          in: path
          required: true
      security:
        - basicAuth: []
      tags:
        - applications
      summary: Returns app's settings by app ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '404':
          description: User not found
components:
  schemas:
    TicketStatusEnum:
      type: string
      enum:
        - new
        - open
        - pending
        - hold
        - solved
        - closed
    TicketDTO:
      type: object
      required:
        - recipient
        - assignee_id
        - comment
        - status
        - subject
        - requester
      properties:
        recipient:
          type: string
          format: email
          description: The email to send from
        assignee_id:
          type: number
          description: Agent ID
        comment:
          type: object
          required:
            - html_body
          properties:
            public:
              type: boolean
              description: Indicate if the content should go publicly. Default is true
            html_body:
              type: string
              description: Ticket's content
        status:
          $ref: '#/components/schemas/TicketStatusEnum'
        subject:
          type: string
          description: Ticket's subject
        tags:
          type: array
          items:
            type: string
        custom_fields:
          type: array
          description: Custom fields to apply to the ticket
          items:
            type: object
            required:
              - id
              - value
            properties:
              id:
                type: number
              value:
                type:
                  string
        requester:
          type: object
          description: The target details to send to
          required:
            - name
            - email
          properties:
            name:
              type: string
            email:
              type: string
              format: email
    Ticket:
      allOf:
        - $ref: '#/components/schemas/TicketDTO'
        - type: object
          required:
            - id
          properties:
            id:
              type: number
    Application:
      type: object
      required:
        - installation
      properties:
        installation:
          type: object
          required:
            - settings
          properties:
            settings:
              type: array
              items:
                type: object
                required:
                  - key
                  - value
                properties:
                  key:
                    type: string
                  value:
                    type: string
    GroupedEmails:
      type: object
      additionalProperties:
        type: string
      example:
        Compliance: "compliance@domain.com, cx@domain.com"
    Group:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: number
        name:
          type: string
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: number
    Macro:
      type: object
      required:
        - id
        - title
        - actions
      properties:
        id:
          type: number
        title:
          type: string
        actions:
          type: array
          items:
            type: object
            required:
              - field
              - value
            properties:
              field:
                type: string
              value:
                type: string
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
security:
  - basicAuth: []
